FROM mysql:8.0

# Variables de entorno para configurar MySQL
ENV MYSQL_DATABASE=wherehouse
ENV MYSQL_ROOT_PASSWORD=1123
ENV MYSQL_TCP_PORT=3306

# Copiar el archivo de inicialización SQL
COPY init.sql /docker-entrypoint-initdb.d/

# Configuración adicional de MySQL para permitir conexiones externas
ENV MYSQL_ROOT_HOST=%

# Puerto expuesto por MySQL
EXPOSE 3306

# Comando para iniciar MySQL con configuración específica
CMD ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--default-authentication-plugin=mysql_native_password"]