FROM mysql:8.0

# Variables de entorno para configurar MySQL
ENV MYSQL_DATABASE=wherehouse
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=password

# Puerto expuesto por MySQL
EXPOSE 3306

# Comando para iniciar MySQL
CMD ["mysqld"]