spring.application.name=warehouse_project


spring.datasource.url=jdbc:mysql://localhost:3306/wherehouse
spring.datasource.username=root
spring.datasource.password=root1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# Configuracion de JPA / Hibernate
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


api.key=AIzaSyAy_Z7JdMcrcFp6zfHevAICt-b4rfENjms

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com


# Habilita la generacion de la documentacion OpenAPI
springdoc.api-docs.enabled=true
# Personaliza la ruta de la UI de Swagger (opcional)
springdoc.swagger-ui.path=/swagger-ui.html